version: "3.7"
services:
  mongo-instance:
    image: mongo
    container_name: "mongo-instance"
    ports:
      - 27017:27017
  springbt-mongodb:
    image: springbt-mongodb
    container_name: springbt-mongodb
    ports:
      - 8080:8080
    links:
      - mongo-instance